BEGIN;

CREATE SCHEMA IF NOT EXISTS charto_landing;

CREATE TABLE IF NOT EXISTS charto_landing.waitlist_registrations (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email               VARCHAR(254) NOT NULL,
  full_name           VARCHAR(120) NOT NULL,
  trading_experience  VARCHAR(24) NOT NULL
    CHECK (trading_experience IN (
      'beginner', 'intermediate', 'experienced', 'professional'
    )),
  source              VARCHAR(32) NOT NULL DEFAULT 'landing',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT waitlist_registrations_email_unique UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS waitlist_registrations_created_at_idx
  ON charto_landing.waitlist_registrations (created_at DESC);

COMMIT;
